CREATE TABLE WEATHER_MEASUREMENT(
   ID BIGINT NOT NULL AUTO_INCREMENT,
   REMOTE_ID BIGINT,
   AMBIENT_TEMPERATURE DECIMAL(6,2) NOT NULL,
   INTERNAL_TEMPERATURE DECIMAL(6,2) NOT NULL,
   EXTERNAL_TEMPERATURE DECIMAL(6,2) NOT NULL,
   AIR_PRESSURE DECIMAL(6,2) NOT NULL,
   HUMIDITY DECIMAL(6,2) NOT NULL,
   SOIL_MOISTURE DECIMAL(6,2) NULL,
   CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY ( ID )
);
